<?php
/**
 * @var $this TBT_OnDemand_Block_InlineManual
 */
?>
<script type="text/javascript">
    window.inlineManualOptions = {
        variables: {
            instance: '<?php echo $this->getInstanceCode(); ?>'
        }
    };
</script>
<script>!function(){var a=document.createElement("script"),b=document.getElementsByTagName("script")[0];a.async=1,a.src="https://inlinemanual.com/embed/player.16f4a936bbed480026f861953b7d199e.js",b.parentNode.insertBefore(a,b)}();</script>